### ISSUE TITLE
[Notice] This repo is abused by random AD providers. Star this repo may cause recieving ads from your github contact mail

### ISSUE THREAD

**Issue by uqsme** [26F-Studio/smartbingo#3]
哥们刚才收到了这样一封电子邮件：

![image](https://github.com/26F-Studio/smartbingo/assets/41455159/2dd1ef56-8c6c-41b6-a9d2-8840ef123116)

我啥时候star过游戏了？哦原来是这个。服了，本来你这玩法就垃圾，还给我引来若至广告🤡

**Comment by MrZ626** [comment]
？这tramolly game是个什么神秘团队，这么发推销邮件不合适吧

**Comment by Neubulae** [comment]
WTF

**Comment by huaji2369** [comment]
WTF

**Comment by MrZ626** [comment]
感觉他们应该不会长期把这推销开着，先close掉吧，还有人反馈就再open

**Comment by TheInterestingS0ul** [comment]
欢迎查看我的个人主页 @RewindBird 捏 😋
我就是超级节奏王，造假王，喜欢到处在别人的地盘上拉屎的Tis有趣的灵魂捏 🤣👉🤡
